---
framework: jest
tier: medium
postMerge: 
  pattern: 
    - "./test/*/*.test.js"
preMerge:
  pattern:Checked mocha repos with updated tas yml file
    - "./test/*/*.test.js"
preRun:
     command:
        - npm install
postRun:
     command:
        - node --version
version: 1.0
