---
framework: jest
blocklist:
   - "test/zones/local.test.js"
   - "test/datetime/zone.test.js"
   - "test/datetime/tokenParse.test.js"
preRun:
     command:
        - npm ci
preMerge:
  pattern:
    - "./test/*/*.test.js"
postMerge: 
  pattern: 
    - "./test/*/*.test.js"
postRun:
     command:
        - node --version
version: 1.5
