---
framework: jest
postMerge: 
  pattern: 
    - "./test/*/*.test.js"
preMerge:
  pattern:
    - "./test/*/*.test.js"
preRun:
     command:
        - npm install
postRun:
     command:
        - node --version
        - node --version
version: 2.0
